### ISSUE TITLE
Push to Haxelib

### ISSUE THREAD

**Issue by Glidias** [wighawag/cosmos#1]
You only have a version 0.4.0 on Haxelib that is broken (missing/empty files) and it points to `/kit`.  Could you push the latest version to Haxelib?

**Comment by wighawag** [comment]
i just deployed 0.5.0 on haxelib
 let me know if you have any issues. I might not be able to work on it until May though

**Comment by Glidias** [comment]
Demo runs fine with haxelib's 0.5.0 as long as I include the other lib dependencies for the demo.
